

COMPONENT_PRIV_INCLUDEDIRS += business
COMPONENT_SRCDIRS += business

COMPONENT_PRIV_INCLUDEDIRS += utf8
COMPONENT_SRCDIRS += utf8


COMPONENT_PRIV_INCLUDEDIRS += business/server
COMPONENT_SRCDIRS += business/server

COMPONENT_PRIV_INCLUDEDIRS += business/xfs
COMPONENT_SRCDIRS += business/xfs

COMPONENT_PRIV_INCLUDEDIRS += business/client
COMPONENT_SRCDIRS += business/client
